### ISSUE TITLE
0.17.0-beta.7 package dependencies issues

### ISSUE THREAD

**Issue by miguelcaires** [jspm/jspm-cli#1538]
Hi. 

Again, on my tests with jspm 0.17.0-beta.7, I came across a dependency management issue. 

Tried installing **angular**, **textAngular**, which generated the **package.json** file below:

```
{
  "jspm": {
    "name": "testing",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.5.0",
      "angular-messages": "github:angular/bower-angular-messages@^1.5.0",
      "textAngular": "github:fraywing/textAngular@^1.5.0"
    },
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.3"
    },
    "peerDependencies": {
      "fs": "github:jspm/nodelibs-fs@^0.2.0-alpha",
      "net": "github:jspm/nodelibs-net@^0.2.0-alpha",
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha",
      "tty": "github:jspm/nodelibs-tty@^0.2.0-alpha",
      "util": "github:jspm/nodelibs-util@^0.2.0-alpha"
    },
    "overrides": {
      "github:angular/bower-angular@1.5.0": {
        "main": "angular",
        "meta": {
          "angular.js": {
            "exports": "angular"
          }
        }
      },
      "github:fraywing/textAngular@1.5.0": {
        "main": "dist/textAngular",
        "files": [
          "dist/**/*"
        ],
        "registry": "jspm",
        "dependencies": {
          "angular": "^1.3.0",
          "css": "*",
          "font-awesome": "^4.0.0",
          "rangy": "^1.3.0"
        },
        "meta": {
          "dist/textAngular.js": {
            "deps": [
              "angular",
              "rangy",
              "rangy/rangy-selectionsaverestore",
              "./textAngularSetup",
              "./textAngular.css!"
            ]
          },
          "dist/textAngular-sanitize.js": {
            "deps": [
              "angular"
            ]
          }
        }
      },
      "github:timdown/rangy-release@1.3.0": {
        "format": "global",
        "main": "rangy-core",
        "meta": {
          "rangy-core.js": {
            "exports": "rangy"
          },
          "rangy-cssclassapplier.js": {
            "deps": [
              "./rangy-core"
            ]
          },
          "rangy-selectionsaverestore.js": {
            "deps": [
              "./rangy-core"
            ]
          },
          "rangy-serializer.js": {
            "deps": [
              "./rangy-core"
            ]
          }
        }
      },
      "npm:font-awesome@4.5.0": {
        "main": "css/font-awesome.css!",
        "jspmNodeConversion": false,
        "registry": "jspm",
        "dependencies": {
          "css": "0.1"
        }
      }
    }
  }
}
```  

These are the contents of **jspm.config.js**:
```
SystemJS.config({
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json",
    "github:*/*.json"
  ],
  transpiler: "plugin-babel",

  map: {
    "angular": "github:angular/bower-angular@1.5.0",
    "angular-messages": "github:angular/bower-angular-messages@1.5.0",
    "fs": "github:jspm/nodelibs-fs@0.2.0-alpha",
    "net": "github:jspm/nodelibs-net@0.2.0-alpha",
    "plugin-babel": "npm:systemjs-plugin-babel@0.0.3",
    "process": "github:jspm/nodelibs-process@0.2.0-alpha",
    "textAngular": "github:fraywing/textAngular@1.5.0",
    "tty": "github:jspm/nodelibs-tty@0.2.0-alpha",
    "util": "github:jspm/nodelibs-util@0.2.0-alpha"
  },

  packages: {
    "testing": {
      "format": "esm"
    },
    "github:fraywing/textAngular@1.5.0": {
      "map": {
        "angular": "github:angular/bower-angular@1.5.0",
        "css": "github:systemjs/plugin-css@0.1.20",
        "font-awesome": "npm:font-awesome@4.5.0",
        "rangy": "github:timdown/rangy-release@1.3.0"
      }
    },
    "npm:font-awesome@4.5.0": {
      "map": {
        "css": "github:systemjs/plugin-css@0.1.20"
      }
    }
  }
});
```

When trying to use textAngular on the prototype, I keep getting the following error:
`Uncaught (in promise) ReferenceError: angular is not defined(…)`

Which leads me to believe that there might be an issue with the way jspm is managing the dependency injection, because it works fine for 0.16.

Any ideas?

Thanks again!

**Comment by guybedford** [comment]
Thanks for posting! Yes I believe I just fixed this in https://github.com/jspm/jspm-cli/commit/49efdec35bd92b48dba61b94d68513e3a2ac12d6 actually.

**Comment by guybedford** [comment]
The work around until the release would be to add `"format": "global"` to all the modules that have "deps" in the overrides.

**Comment by miguelcaires** [comment]
Thanks for the very quick reply. 

Do you mean adding the key to the actual module that has the deps or, in the other hand, add it to a module that is being referenced as a dependency in another one?

Either way, I added it to both angular and textAngular as you can see below, but the problem still persists.

```
{
  "jspm": {
    "name": "testing",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.5.0",
      "angular-messages": "github:angular/bower-angular-messages@^1.5.0",
      "textAngular": "github:fraywing/textAngular@^1.5.0"
    },
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.3"
    },
    "peerDependencies": {
      "fs": "github:jspm/nodelibs-fs@^0.2.0-alpha",
      "net": "github:jspm/nodelibs-net@^0.2.0-alpha",
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha",
      "tty": "github:jspm/nodelibs-tty@^0.2.0-alpha",
      "util": "github:jspm/nodelibs-util@^0.2.0-alpha"
    },
    "overrides": {
      "github:angular/bower-angular@1.5.0": {
        "format": "global",
        "main": "angular",
        "meta": {
          "angular.js": {
            "exports": "angular"
          }
        }
      },
      "github:fraywing/textAngular@1.5.0": {
        "format": "global",
        "main": "dist/textAngular",
        "files": [
          "dist/**/*"
        ],
        "registry": "jspm",
        "dependencies": {
          "angular": "^1.3.0",
          "css": "*",
          "font-awesome": "^4.0.0",
          "rangy": "^1.3.0"
        },
        "meta": {
          "dist/textAngular.js": {
            "deps": [
              "angular",
              "rangy",
              "rangy/rangy-selectionsaverestore",
              "./textAngularSetup",
              "./textAngular.css!"
            ]
          },
          "dist/textAngular-sanitize.js": {
            "deps": [
              "angular"
            ]
          }
        }
      },
      "github:timdown/rangy-release@1.3.0": {
        "format": "global",
        "main": "rangy-core",
        "meta": {
          "rangy-core.js": {
            "exports": "rangy"
          },
          "rangy-cssclassapplier.js": {
            "deps": [
              "./rangy-core"
            ]
          },
          "rangy-selectionsaverestore.js": {
            "deps": [
              "./rangy-core"
            ]
          },
          "rangy-serializer.js": {
            "deps": [
              "./rangy-core"
            ]
          }
        }
      },
      "npm:font-awesome@4.5.0": {
        "main": "css/font-awesome.css!",
        "jspmNodeConversion": false,
        "registry": "jspm",
        "dependencies": {
          "css": "0.1"
        }
      }
    }
  }
}
```

Am I misplacing the `"format": "global"` or is it a bigger issue than that? 

Thanks!

**Comment by guybedford** [comment]
You need to run `jspm install` after editing overrides in the package.json for them to take effect. Otherwise edit the package config files directly in the jspm_packages folder, as described in the jspm beta guide.

**Comment by miguelcaires** [comment]
That does it! 
Thank you!

**Comment by guybedford** [comment]
Released in 0.17.0-beta.8.
