### ISSUE TITLE
Unable to use npm:superagent (failed to require 'emitter') on 0.17.0-beta.7; works on 0.16.29

### ISSUE THREAD

**Issue by AdamBurgess** [jspm/jspm-cli#1548]
Tested on 0.17.0-beta.7/6/5/4/2/1 (beta.3 had some error about plugin-babel but that's probably unrelated).
Nothing done but `npm install jspm@0.17.0-beta.7 && jspm init && jspm install npm:superagent`

src/main.js:
```js
import superagent from 'superagent'
export default {}
```
console (from `jspm run src/main.js`)
```
err  Error: ENOENT: no such file or directory, open 'O:\Projects22-JSPMServer2\emitter'
  Error loading file:///O:/Projects22-JSPMServer2/emitter as "emitter" from file:///O:/Projects22-JSPMServer2/jspm_packages/npm/superagent@1.7.2/lib/client.js
    at Error (native)
```

console (from browser)
```
system.src.js:4868 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://127.0.0.1:8888/emitter
	Error loading http://127.0.0.1:8888/emitter as "emitter" from http://127.0.0.1:8888/jspm_packages/npm/superagent@1.7.2/lib/client.js
    at o (http://127.0.0.1:8888/jspm_packages/system.js:4:13330)
    at XMLHttpRequest.s.onreadystatechange (http://127.0.0.1:8888/jspm_packages/system.js:4:13918)
```

The dependency `npm:component-emitter` is installed, but `superagent@1.7.2/lib/client.js` uses 
```js
var Emitter = require('emitter');
```

On 0.16.29, superagent is successfully imported along with component-emitter (again, nothing fancy but `npm install jspm && jspm init && jspm install npm:superagent`):
![](http://qs.lc/sdz72)

**Comment by AdamBurgess** [comment]
After a little bit of researching, turns out that there is an override for superagent -- https://github.com/jspm/registry/blob/master/package-overrides/npm/superagent@1.0.0.json. Removing that gets `jspm run` to work fine, as it loads the `lib/node/index.js` instead of `lib/client.js`.

The problem of not mapping `component-emitter` to `emitter` still remains for the browser, though.

I believe that is due to these lines in jspm-npm/lib/node-conversion.js, https://github.com/jspm/npm/blob/4cf97a6e07aa9066fe7c73fb6116bd24fa6a484d/lib/node-conversion.js#L134-L138
As https://github.com/systemjs/systemjs/issues/937 is fixed now, is checking if the mapping fields start with `./` necessary any more? Without that, everything works perfectly.

I'll close this and make another issue in jspm/npm. If that override to superagent isn't needed, then I guess that should be removed also.

**Comment by guybedford** [comment]
@AdamBurgess should we remove the override for Superagent then? Will the browser map still work correctly in jspm 0.16 do you think?

**Comment by mamciek** [comment]
I belive this is still not fixed. Superagent does not work in browser
