### ISSUE TITLE
[0.17-beta.14] 'Cannot read property match of null' when bundling

### ISSUE THREAD

**Issue by jackfranklin** [jspm/jspm-cli#1846]
Getting the following error when trying to build a test bundle:

```js
~/git/talks/client-side-jspm > jspm bundle index.js -wid
     Building the bundle tree for index.js...

err  TypeError: Cannot read property 'match' of null
    at /Users/jackfranklin/git/talks/client-side-jspm/node_modules/systemjs-builder/lib/sourcemaps.js:62:25
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at /Users/jackfranklin/git/talks/client-side-jspm/node_modules/systemjs-builder/lib/sourcemaps.js:61:24
    at Array.forEach (native)
    at exports.concatenateSourceMaps (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/systemjs-builder/lib/sourcemaps.js:42:19)
    at createOutput (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/systemjs-builder/lib/output.js:63:21)
    at exports.writeOutputs (/Users/jackfranklin/git/talks/client-side-jspm/node_modules/systemjs-builder/lib/output.js:150:16)
    at /Users/jackfranklin/git/talks/client-side-jspm/node_modules/systemjs-builder/lib/builder.js:607:14
    at try
```

All I've done is follow the beta guide. 

Repo is here: https://github.com/jackfranklin/jspm-017

To  recreate:

- clone repo
- npm install
- jspm install
- jspm bundle index.js -wid

Going to dig into the source to see if I can figure anything out.

**Comment by jackfranklin** [comment]
The line in systemjs-builder causing this is:

```
if (mapping.source.match(/(\/|^)@traceur/))
```

I can also fix this bug by turning it into:

```
      if (!mapping.source)
        return;

      if (mapping.source.match(/(\/|^)@traceur/))
        return;

```

However, I don't know if this is a good idea or the right fix...

**Comment by guybedford** [comment]
Thanks, I think this is fixed in the latest SystemJS builder release, so should come through with the next jspm. Working on getting out that release asap.

**Comment by jackfranklin** [comment]
👍  great, thanks! In theory then in the mean time I can install the latest systemjs-builder and that should work?

**Comment by guybedford** [comment]
Yes it should do.

**Comment by jackfranklin** [comment]
@guybedford tried both 0.15.17 and also systemjs/builer#master and the bug is still present unfortunately.

**Comment by jackfranklin** [comment]
@guybedford sorry for the false comment above, can confirm this is fixed with systemjs-builder 0.15.17

**Comment by guybedford** [comment]
👍 thanks for confirming, will close this then.
