### ISSUE TITLE
[0.17-beta15] Conditional loading not working

### ISSUE THREAD

**Issue by lmaze** [jspm/jspm-cli#1858]
Hi there,

It seems that the conditional loading is not working properly in the latest 0.17 beta (beta 15).

I tried to make a new simple project to test this functionality.
I followed this documentation : [http://jspm.io/0.17-beta-guide/conditional-loading.html](http://jspm.io/0.17-beta-guide/conditional-loading.html).

I just have a simple class in a '_app.js_' file that import '_text.js_', exactly as in the example of documentation.

```
import text from './text.js';
export class HelloWorld {
    // ....
}
```

In the _jspm.config.js_ file I have declared a map configuration inside my package :

```
packages: {
  "app": {
    "main": "app.js",
    "format": "esm",
    "meta": {
      "*.js": {
        "loader": "plugin-babel"
      }
    },
    "map": {
      "./text.js": {
        "~production": "./text-dev.js"
      }
    }
  }
}
```

The rest of the configuration is a standard configuration.
  
When I run the bundle command (with : `jspm bundle src/app.js dist/app-bundle.js`), I get the following error:

```
Building the bundle tree for src/app.js...
err  TypeError: Cannot read property 'map' of undefined
    at K:\devhome\app\nvm\v6.2.0\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:237:39
```

I thought there might be a mistake in the documentation and the map configuration should not be inside a package.

So I tried the following configuration:
```
packages: {
  "app": {
    "main": "app.js",
    "format": "esm",
    "meta": {
      "*.js": {
        "loader": "plugin-babel"
      }
    }
  }
},
map: {
  "./text.js": {
    "~production": "./text-dev.js"
  }
}
  ```

It's a little better because the bundle is achieved.
```
Building the bundle tree for src/app.js...

       app/app.js
       app/text.js
       npm:systemjs-plugin-babel@0.0.11.json
       npm:systemjs-plugin-babel@0.0.11/babel-helpers/classCallCheck.js

ok   Built into dist\app-bundle.js with source maps, unminified.
```

But when I ask to include only the development branch (with the command: `jspm bundle src/app.js dist/app-bundle.js --dev`), the result is the same and the '_text-dev.js_' is never taken into account.

I also tried to set a `production` boolean property in _jspm.browser.js_ to false but the result is still the same.

**Comment by lmaze** [comment]
I just tested with the beta 14 and my first test case.
```
packages: {
  "app": {
    "main": "app.js",
    "format": "esm",
    "meta": {
      "*.js": {
        "loader": "plugin-babel"
      }
    },
    "map": {
      "./text.js": {
        "~production": "./text-dev.js"
      }
    }
  }
}
```
Everything works as expected when using the bundle command.

So I confirm that there is a bug in the beta 15 and 16.

**Comment by guybedford** [comment]
Thanks, I think this was fixed in https://github.com/systemjs/builder/commit/36b9c7c4d9189fe9f1ca6647538d73ff7da8b84e.

**Comment by guybedford** [comment]
(for the next release)

**Comment by guybedford** [comment]
The workaround may be to use `"dev"` instead of `"~production"`.

**Comment by lmaze** [comment]
I do not think that the commit you mention fix the problem.
I tried a config not using a negation (directly `production` instead `~production`):

```
packages: {
    "app": {
      "format": "esm",
      "main": "app.js",
      "map": {
        "./text.js": {
            "production": "./text-prod.js"
        }
      },
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
```

When I run the bundle command (`jspm bundle app --production`) I still have the following problem:
```
Building the bundle tree for app...

err  TypeError: Cannot read property 'map' of undefined
    at K:\devhome\app\nvm\v6.2.0\node_modules\jspm\node_modules\systemjs-builder\lib\trace.js:237:39
```

I also tried a config with `dev` instead `~production` a as you suggest and the problem is still here.

(Also tried with Node 4.4.4).

**Comment by guybedford** [comment]
Yes you're right - fixed in https://github.com/systemjs/builder/commit/4315a9e66b294f0f9a7fb73bee679343a111a6c1.

**Comment by lmaze** [comment]
Great, thank you for the quick fix!

**Comment by guybedford** [comment]
Released in 0.17.0-beta.17.

**Comment by lmaze** [comment]
I confirm that everything is back to normal with the latest release. Many thanks!
