### ISSUE TITLE
CSS loader does not work on windows

### ISSUE THREAD

**Issue by Mau04** [jspm/jspm-cli#403]
Please check out this sample project:
https://github.com/Mau04/jspm-css-win
TWBS CSS files are not loaded on Windows. On OS X, everything works fine.
Could someone please have a look?

**Comment by Barguast** [comment]
Same issue. The JS part of Bootstrap seems to startup, but the CSS doesn't seem to be applied

**Comment by guybedford** [comment]
Thanks for reporting this - I've included a fix in https://github.com/jspm/jspm-cli/commit/6f49d8237df2e8cdba0a83ae8db6740f43cecd40.

**Comment by Mau04** [comment]
It still does not work. I updated the sample project to 0.10.6, but it still does not load twbs css.

**Comment by jamiewinder** [comment]
Yep, just tried updating and I'm still seeing the same. 

Forgive me if I'm wrong, but I think the cause seems to be the JS file that is used to initialise: (bootstrap@3.3.1,js):
```
module.exports = require("github:twbs/bootstrap@3.3.1/js/bootstrap");
```
It doesn't even attempt to load the CSS. I've fixed the issue temporarily by changing this file to:

```
var Bootstrap = require("github:twbs/bootstrap@3.3.1/js/bootstrap");
require("github:twbs/bootstrap@3.3.1/css/bootstrap.css!");

module.exports = Bootstrap;
```

**Comment by guybedford** [comment]
@Mau04 did you try running `jspm install bootstrap -f`?

**Comment by SekibOmazic** [comment]
Hi,

I didn't want to open a new issue because this is more something like "request for help" than an issue. I build my application with:
```Shell
jspm bundle-sfx lib/app --minify
```
Bundle-sfx works fine and application starts. The only thing is that the bootstrap css doesn't get loaded. I see following message in browser's console:
```Shell
SystemJS Builder - Plugin for github:twbs/bootstrap@3.3.2/css/bootstrap.css!github:systemjs/plugin-css@0.1.0 does not support sfx builds
```

Could you please shed some light on this?

Thanks!

**Comment by guybedford** [comment]
@SekibOmazic CSS builds are not yet supported, this is being tracked at https://github.com/systemjs/builder/issues/12.

**Comment by SekibOmazic** [comment]
@guybedford OK, thanks.

**Comment by guybedford** [comment]
This should be working now, please let me know if there are any more issues with this at all.

**Comment by SekibOmazic** [comment]
@guybedford So I just need fresh new jspm-cli release, right?

**Comment by guybedford** [comment]
Yes it should work with 0.10.6.

**Comment by SekibOmazic** [comment]
@guybedford Sorry to bother you again, bit it doesn't work for me. I still get the same message. 

The `jspm` is in version 0.10.6 and SystemJS v0.11.3. 
Browser cache flushed and the app built with `jspm bundle-sfx lib/app --minify` but no luck.

**Comment by guybedford** [comment]
@SekibOmazic I was referring to the original issue, CSS builds are still being tracked at https://github.com/systemjs/builder/issues/12.

**Comment by SekibOmazic** [comment]
@guybedford Sorry, my fault.
