### ISSUE TITLE
iojs support

### ISSUE THREAD

**Issue by capaj** [jspm/jspm-cli#410]
Using io.js 1.0.2 and Windows(will try on Ubuntu tommorow), I am unable to download any github packages. No error is shown-jspm just hangs there undefinately either on 
```
Updating registry cache...
``` 
or on 
```
Downloading github:urish/angular-moment@0.9.0
```

This happens with some github packages or NPM. I have got this problem with bootstrap, angular-moment so far and few others so far.

**Comment by guybedford** [comment]
@capaj sure, I will need to check if io.js is supported! Are you saying it gets past that issue and does start downloading, only getting stuck occasionally?

**Comment by capaj** [comment]
@guybedford no, always for some packages. For ther packages it always works.

**Comment by BuildingJarl** [comment]
I noticed the same thing. 

Temp solution
cancel command (ctrl-c) after a couple of minutes then reenter it

![image](https://cloud.githubusercontent.com/assets/5493114/5819089/05abd4ea-a0b3-11e4-8284-4a980cfeef73.png)

**Comment by konsumer** [comment]
I can confirm with io.js v1.0.3

**Comment by capaj** [comment]
@BuildingJarl yes while you can try again and it will go through, for me the file which says 
```javascript
module.exports = require("github:angular/bower-material@0.6.1/angular-material");
```
is not created, hence your app will fail if you require('angular-material').
I guess this file is created only after downloading from github. When files are there already, JSPM does not create the public/jspm_packages/github/angular/bower-material@0.6.1.js file.

**Comment by guybedford** [comment]
It sounds like this is an issue for downloading the release archives then? That would correspond to this code - https://github.com/jspm/github/blob/master/github.js#L355.

I haven't been able to replicate this myself yet in a test case. Could it just be slow downloads though?

Any further help isolating / debugging would be greatly appreciated.

**Comment by capaj** [comment]
No way this is just slow download. I get this on 100 Mbit connection. Will
try to look at the code and isolate the culprit.

Dne čt, 22. 1. 2015 15:11 uživatel Guy Bedford <notifications@github.com>
napsal:

**Comment by guybedford** [comment]
Can you confirm these are all iojs issues? iojs is not currently supported.

**Comment by guybedford** [comment]
I've tested with iojs and can confirm that the GitHub release downloads are stalling. Updating request helped, leading to this request - https://github.com/jspm/github/blob/master/github.js#L493 sometimes returning a response and sometimes stalling.

I'm not really sure what this could be. Backwards-incompatible changes like this are not ideal. I'd like to say that iojs is officially unsupported, but contributions to help get support with bugs like these is welcome.

**Comment by guybedford** [comment]
https://github.com/jspm/jspm-cli/issues/432 seems to be another unrelated issue for iojs support.

**Comment by capaj** [comment]
I tried on Ubuntu just now github:urish/angular-moment, superagent from npm, angular-material and some other packages with io.js 1.04 and jspm 0.10.6 and all worked on first try.
Let me try on windows too.

**Comment by guybedford** [comment]
Specifically it is the GitHub release downloads that aren't working (Bootstrap, d3, three.js)

**Comment by capaj** [comment]
@guybedford I confirm these are all iojs issues. On node it works every time.

**Comment by BuildingJarl** [comment]
@guybedford  I can also confirm that these are iojs issues. Currently using JSPM with node and installs are working

**Comment by jimthedev** [comment]
There is a list of non-working io.js modules and it appears people are going through the list and putting in PRs. Perhaps one of them will see something useful here: https://github.com/iojs/io.js/issues/456

**Comment by u9520107** [comment]
I even got jspm to work on raspberry pi 2 with node 0.11.14...
But failed with the latest iojs.

**Comment by guybedford** [comment]
I had a look at this again today, and the problem actually seems to be that somehow the CPU is getting caught in a loop. I tried to get node-inspector to work but apparently it doesn't support io.js yet. If anyone knows how to work dtrace, help seeing where in the stack it's getting caught up would be very welcome.

**Comment by jimthedev** [comment]
Link to the node-inspector issue that corresponds to iojs support: https://github.com/node-inspector/node-inspector/issues/523

**Comment by jimthedev** [comment]
I was able to build node-inspector with iojs by just bumping it's dependency v8-debug to version 0.4.0. I've put in a PR with node-inspector.  I'm not sure how best to use inspector to find what is going on but will certainly try.

**Comment by guybedford** [comment]
Thanks @jimthedev - the ncp update has helped, but there is still a CPU issue unfortunately when downloading. The test I'm running is `jspm install -f` in the `testlibs` folder of this repo.

**Comment by jimthedev** [comment]
Thanks. I'll take a look.

**Comment by jimthedev** [comment]
So, I've finally been able to reproduce the 100% cpu problem. My nvm was back at system so I wasn't seeing the issue before. To diagnose I am running the following:

```bash
iojs --prof /Users/jcummins/bin/npm/bin/jspm install npm:superagent
```

let this run for a while and hang, then Ctrl-C and run the following (replacing XXXXXXX with the timestamp):

```bash
sudo npm install -g node-tick-processor
node-tick-processor isolate-0xXXXXXXXX-v8.log > isolate-XXXXXXXXXX-v8.log.tick
vim isolate-XXXXXXXXXX-v8.log.tick
```

ncp is churning. Was able to track down what the ember-cli team did which is to use their own fork of node-copy-dereference instead of using ncp. You can see 100% cpu in reference to ncp mentioned [in this comment](https://github.com/ember-cli/ember-cli/issues/2991#issuecomment-71362767) and it was eventually addressed in this commit: https://github.com/johanneswuerbach/ember-cli/commit/6d5ddce27b86eaac1df3a600992456d2ebd05bcd

I haven't had a chance to test this yet but would suspect that this could very well be the problem.

**Comment by guybedford** [comment]
Amazing! Thanks so much for figuring this out, never would have found that.

I've just pushed https://github.com/jspm/jspm-cli/commit/6d2502432dc2c606c96893cd0c75c2810e5a2366 which has got iojs support working for me. Will post a release shortly.

**Comment by guybedford** [comment]
io.js support is now working. Big thanks to @jimthedev.

**Comment by konsumer** [comment]
Thanks  @jimthedev!

**Comment by jimthedev** [comment]
@konsumer No problemo. There may be other issues but at least this gets us rolling. Thanks for the quick release @guybedford!

**Comment by dkushner** [comment]
Can anyone confirm what jspm version this was released under? Still getting the same issue with iojs v2.2.1 and jspm@0.16.0-beta.
