### ISSUE TITLE
--debug flag in jspm

### ISSUE THREAD

**Issue by dvc94ch** [jspm/jspm-cli#873]
I'm looking into adding a --debug flag to jspm install, I figure it's going to save me a lot of time...

What is the --dev flag for? Is it already reserved / can it be used for such a purpose?

**Comment by guybedford** [comment]
Sure, note `--dev` is for development dependency installs. Discussion about log level flags has been in https://github.com/jspm/jspm-cli/issues/528 so far.

**Comment by guybedford** [comment]
@dvc94ch from https://github.com/jspm/jspm-cli/issues/528#issuecomment-114990026 it sounds like your specific case is having the endpoint errors get thrown explicitly? So more of a `--registry-debug` flag then?

**Comment by dvc94ch** [comment]
That would be a simple solution.
```
if (!options['registry-debug'])
  throw "Nice error";
```
So would you be ok with something like this then?

**Comment by guybedford** [comment]
Yes that sounds reasonable!

**Comment by guybedford** [comment]
I'm wondering if we shouldn't just always show error stacks for these endpoint hooks though, only showing the "nice errors" when there is no error object provided to the rejection handler (ie for Timeouts which is what this use case is really all for).

**Comment by guybedford** [comment]
Sorry about this - it's a bad debugging experience in the name of giving nice errors to users, which is completely daft.

**Comment by dvc94ch** [comment]
So what's the solution here? Just remove the `throw "Nice error"` will do then?

**Comment by dvc94ch** [comment]
I guess there isn't really a point to nice errors. If someone really doesn't know what to do with a stacktrace, he'll go asking for help without one and then he'll just be told run --registry-debug, which is just a waste of everyone's time...

**Comment by guybedford** [comment]
@dvc94ch specifically which hook is this for? For example download error stacks display fine for me.

**Comment by dvc94ch** [comment]
It's mainly the `Error processing package config for ...` that's annoying me at the moment.
[https://github.com/jspm/jspm-cli/blob/master/lib/package.js#618](https://github.com/jspm/jspm-cli/blob/master/lib/package.js#618)
It's catching the error and throwing a generic useless one...

**Comment by guybedford** [comment]
I'm definitely getting an error stack this side for that hook actually.

**Comment by guybedford** [comment]
And you're definitely installing with the `-f` flag? A test case may help to look at this further.

**Comment by dvc94ch** [comment]
This is what I get usually:
```
[dvc@system76 tests]$ jspm install -f ml:json

warn Running jspm globally, it is advisable to locally install jspm via npm install jspm --save-dev.
     Looking up ml:json
     Updating registry cache...
     Downloading ml:json@1.0.3
processing

warn Error processing package config for ml:json.

err  Error processing package config for ml:json.

warn Installation changes not saved.
```
This is what I get when I comment it out:
```
warn TypeError: Cannot read property 'dependencies' of undefined
         at /home/dvc/workspace/jspm/lib/package.js:408:37
         at lib$rsvp$$internal$$tryCatch (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at doNTCallback0 (node.js:408:9)
         at process._tickCallback (node.js:337:13)

err  TypeError: Cannot read property 'registry' of undefined
         at Object.exports.processPackage (/home/dvc/workspace/jspm/lib/package.js:640:37)
         at /home/dvc/workspace/jspm/lib/package.js:563:23
         at lib$rsvp$$internal$$tryCatch (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at doNTCallback0 (node.js:408:9)
         at process._tickCallback (node.js:337:13)

warn Installation changes not saved.
```
and this is still hiding the actual problem. to find the actual problem I have to add
```
dependencies: {},
        jspm: {
          registry: 'npm'
        }
```
to pjson to see what the actual problem is. When everything works correctly those aren't needed...

**Comment by guybedford** [comment]
Thanks! Ok right, so this is a sort of usability bug at the level of registry creation. Basically the error of `pjson` not being an object in https://github.com/jspm/jspm-cli/blob/master/lib/package.js#L614 is being masked as a registry error itself.

I've pushed a fix in https://github.com/jspm/jspm-cli/commit/ee1ad02691f2fd6e83c93f45d80556b80e4281df. Do let me know if you notice anything else like this.

**Comment by dvc94ch** [comment]
it still seems to be masking the problem, this works like expected...
```
.catch(function(error) {
    throw error; //'Error processing package config for `' + pkg.name + '`.';
  });
```

**Comment by dvc94ch** [comment]
Or removing the entire .catch block. Then you get the new Error your throwing that's more descriptive... Otherwise you still get the `Error processing package config` message...

**Comment by dvc94ch** [comment]
And by the way if pjson is undefined you get a different error message that isn't caught by your change:
```
err  TypeError: Cannot read property 'jspm' of undefined
         at Object.exports.derivePackageConfig (/home/dvc/workspace/jspm/lib/config.js:38:24)
         at derivePackageConfig (/home/dvc/workspace/jspm/lib/package.js:609:18)
         at Promise.resolve.then.then.then.pjson (/home/dvc/workspace/jspm/lib/package.js:522:20)
         at lib$rsvp$$internal$$tryCatch (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at doNTCallback0 (node.js:408:9)
         at process._tickCallback (node.js:337:13)
```

**Comment by dvc94ch** [comment]
The error:
```
warn TypeError: Cannot read property 'dependencies' of undefined
         at /home/dvc/workspace/jspm/lib/package.js:408:37
         at lib$rsvp$$internal$$tryCatch (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at doNTCallback0 (node.js:408:9)
         at process._tickCallback (node.js:337:13)

err  TypeError: Cannot read property 'registry' of undefined
         at Object.exports.processPackage (/home/dvc/workspace/jspm/lib/package.js:640:37)
         at /home/dvc/workspace/jspm/lib/package.js:563:23
         at lib$rsvp$$internal$$tryCatch (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:489:16)
         at lib$rsvp$$internal$$invokeCallback (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:501:17)
         at lib$rsvp$$internal$$publish (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:472:11)
         at lib$rsvp$asap$$flush (/home/dvc/workspace/jspm/node_modules/rsvp/dist/rsvp.js:1290:9)
         at doNTCallback0 (node.js:408:9)
         at process._tickCallback (node.js:337:13)

warn Installation changes not saved.
```
happens when `processPackageConfig()` doesn't return `pjson`

**Comment by dvc94ch** [comment]
ups sry, mixed processPackageConfig() up with getPackageConfig(), so yes the error message is ok, it's just caught by the catch block...

**Comment by guybedford** [comment]
No problem, yes I expect we'll find this for all the hooks.

**Comment by dvc94ch** [comment]
Thank you. I guess this issue can be closed then...
